### ISSUE TITLE
Include translators

### ISSUE THREAD

**Issue by leo1200** [garethbjohnson/gutendex#12]
I would really appreciate translators being included, i.e. for instance for https://www.gutenberg.org/ebooks/39402
{
  id: 39402,
  title: 'Jeremiah: A Drama in Nine Scenes',
  authors: [ { name: 'Zweig, Stefan', birth_year: 1881, death_year: 1942 } ],
  **translators: [{name: 'Cedar, Paul', birth_year: 1880, death_year: 1972 }, {name: 'Eden, Paul', birth_year: 1865, death_year: 1944 }]**
  ...
}

Thanks in advance & for this great project in general

Leonard

**Comment by garethbjohnson** [comment]
Hi Leonard, thank you for the idea! It seemed quite easy to do, so I have done it. Feel free to me know if you find any issues with it.

**Comment by leo1200** [comment]
Thanks for implementing my idea so quickly :)

**Comment by leo1200** [comment]
One more question: I am using Windows and it would be a lot more convenient for me to just query gutendex.com instead of trying to make a local version available to me (by installing Ubuntu or using a Linux subsystem) (I only use the simple book/id query).  Is that OK (I may need to go trough the whole catalogue once but can split it over time if that helps)?

**Comment by garethbjohnson** [comment]
Yes, that sounds fine. If you notice the site becoming very slow or unresponsive, though, then try to slow down. 😁
