### ISSUE TITLE
Deploy gutendex on heroku.com

### ISSUE THREAD

**Issue by phr85** [garethbjohnson/gutendex#19]
Hello

I try to deploy gutendex on heroku.com. But I don't know exactly how to do it. What I did so far:

Create "Procfile" file:
`release: pip install gunicorn && python manage.py migrate && python manage.py updatecatalog && python manage.py collectstatic
web: gunicorn gutendex.wsgi`

Catalog (DB) is now generated. But somehow Server always crash on start up:
<img width="1298" alt="Screenshot 2021-10-22 at 15 21 08" src="https://user-images.githubusercontent.com/1322091/138461332-97df3fe1-3b12-414a-9807-a27ca41fbbc7.png">

Maybe someone can help me?

**Comment by garethbjohnson** [comment]
I did not add a "runtime.txt", but it seems to use Python 3.9.7. (I also had to update the version of `psycopg2` to `2.9.1` in "requirements.txt", but I don't know if that's related to the Python version.)

For STATIC_ROOT, I used "/var/www/gutendex/static", but I think the `django_heroku` package overrides this anyway, and a blank value seems to work for me, too. If updating the Python and `psycopg2` versions doesn't work, try making sure in "gutendex/settings.py" you are importing `django_heroku` at the top and have this at the bottom: `django_heroku.settings(locals())`

**Comment by phr85** [comment]
Hello @garethbjohnson 
Thank you for your help.
I did exactly what you advice me. It run through processes but in end somehow server not really run (crashing). Any idea what else I could try?


![Screenshot 2021-10-30 at 11 02 16](https://user-images.githubusercontent.com/1322091/139526988-1ec19193-146c-4a4e-a5fe-1490899e08a2.png)
![Screenshot 2021-10-30 at 11 02 06](https://user-images.githubusercontent.com/1322091/139526990-9b821813-34d4-4c78-a570-68734669dcab.png)
![Screenshot 2021-10-30 at 11 01 58](https://user-images.githubusercontent.com/1322091/139526991-96a936d2-226e-4c5d-a336-d932db1a266c.png)

**Comment by garethbjohnson** [comment]
Ah, I think you now just need to add the line `gunicorn==20.1.0` to your "requirements.txt". (Also make sure you have `django-heroku==0.3.1`.)

**Comment by phr85** [comment]
@garethbjohnson 
YES! Thank you very much, now is working!
