### ISSUE TITLE
Thankyou!

### ISSUE THREAD

**Issue by starry-shivam** [garethbjohnson/gutendex#29]
So i created this issue just to say a personal Thank You for creating this amazing API! ♥️ (_as i couldn't find any other ways to connect with you_)

I've been using your API from very long time in some of my personal python scripts etc and recently made an [Android app](https://github.com/Pool-Of-Tears/Myne) so the general people could also benefit from the amazing book catalogue of the project Gutenberg (since the official website doesn't seems very optimised with mobile devices).

The project might not be possible or would've taken a lot of work and time without this amazing API of yours. So thanks again for creating such an useful stuff!

PS: feel free to close this issue after you see it :)

**Comment by peterrauscher** [comment]
I also want to take this opportunity to say my thanks! Your API is beautifully designed and it inspired me to create a python module to provide access to it. Check it you if you'd like!
[https://github.com/peterrauscher/py-gutenberg](https://github.com/peterrauscher/py-gutenberg)
