### ISSUE TITLE
Adding "page count" to the reply data

### ISSUE THREAD

**Issue by DavidLazarescu** [garethbjohnson/gutendex#30]
Is there a way to add the page count to the json reply? It would be very useful if that's possible

**Comment by garethbjohnson** [comment]
Unfortunately, Project Gutenberg do not seem to give page counts. It might be possible to automatically download each book PDF and count the pages, or search each book with some other book API that has gives counts, but I want to restrict Gutendex to only data from Project Gutenberg

**Comment by DavidLazarescu** [comment]
I understand, thanks
